apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: apisix
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 9080
    name: http
  - port: 9180
    targetPort: 9180
    name: admin
  selector:
    app: apisix