name: apisix-traditional

services:
  etcd:
    image: bitnami/etcd:latest
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
    ports:
      - "2379:2379"
    healthcheck:
      test: "etcdctl endpoint health"
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      apisix:

  apisix:
    image: apache/apisix:latest
    depends_on:
      etcd:
        condition: service_healthy
    volumes:
      - ./conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "9080:9080/tcp"
      - "9443:9443/tcp"
      - "9180:9180/tcp"
      - "9091:9091/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

  httpbin:
    image: kennethreitz/httpbin:latest
    ports:
      - "3000:80/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
