upstreams:
  # Upstream to internal service
  - id: httpbin_internal
    nodes:
      "httpbin:80": 1
    type: roundrobin

routes:
  # Simple route to internal service
  - id: internal_base
    uri: /anything
    upstream_id: httpbin_internal
    
  # Rewrite URI
  - id: internal_rewrite
    uri: /httpbin/*
    upstream_id: httpbin_internal
    plugins:
      proxy-rewrite:
        regex_uri:
          - ^/httpbin/(.*)
          - /$1

#END
