upstreams:
  # Upstream to internal service
  - id: internal_httpbin
    nodes:
      "httpbin-standalone:80": 1
    type: roundrobin

routes:
  # Simple route to internal service
  - id: base_internal
    uri: /anything
    upstream_id: internal_httpbin
    
  # Rewrite URI
  - id: httpbin_internal
    uri: /httpbin/*
    upstream_id: internal_httpbin
    plugins:
      proxy-rewrite:
        regex_uri:
          - ^/httpbin/(.*)
          - /$1

#END
