apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: "default"
  labels:
    app.kubernetes.io/name: httpbin
    app.kubernetes.io/instance: httpbin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: httpbin
      app.kubernetes.io/instance: httpbin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: httpbin
        app.kubernetes.io/instance: httpbin
    spec:
      containers:
        - name: httpbin
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 10
            httpGet:
              path: /get
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 10
            httpGet:
              path: /get
              port: http
          resources: {}
